# Generated by Django 5.2.12 on 2026-03-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('can_create_teacher', 'Puede crear profesores'), ('can_create_student', 'Puede crear estudiantes'), ('can_create_parent', 'Puede crear acudientes')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AddField(
            model_name='user',
            name='parent_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='student_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
