# Generated by Django 5.2.12 on 2026-03-24 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('academic_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.academicperiod')),
                ('teacher_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='academics.teacherassignment')),
            ],
        ),
        migrations.CreateModel(
            name='GradeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='grades.activity')),
            ],
        ),
    ]
