# Generated by Django 5.2.12 on 2026-03-24 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('videocalls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocall',
            name='recording_url',
        ),
        migrations.RemoveField(
            model_name='videocall',
            name='token',
        ),
        migrations.AlterField(
            model_name='callinvitation',
            name='invited_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='call_type',
            field=models.CharField(choices=[('private', 'Privada'), ('class', 'Clase'), ('parent_meeting', 'Reunión de Padres')], max_length=20),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='channel_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.grade'),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='teacher_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.teacherassignment'),
        ),
    ]
