# Generated by Django 5.2.12 on 2026-03-24 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='grade',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='academicperiod',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.grade'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='school_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolyear'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'school_year')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'grade', 'subject', 'school_year')},
        ),
    ]
