# Generated by Django 5.2.12 on 2026-03-24 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('attendance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='teacher_assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.teacherassignment'),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'teacher_assignment', 'date')},
        ),
    ]
